on: [pull_request]

name: Build and Test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          yarn install && \
          cd ./packages/plugins/plugin-build && \
          yarn release
      - name: Build Example
        run: |
          yarn build --ignore-cache packages/examples/lorem-ipsum/
      - name: Test
        run: |
          yarn test --ignore-cache
