on:
  push:
    tags:
      - "v*"

name: Upload Release Asset

jobs:
  build:
    name: Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          yarn install && \
          cd ./packages/plugins/plugin-build && \
          yarn release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./packages/plugins/plugin-build/bundles/@yarnpkg/plugin-build.js
          asset_name: "plugin-build.js"
          asset_content_type: text/javascript

      - name: Update release
        run: |
          export TAGNAME=$(echo "${{ github.ref }}" | sed 's|refs/tags/||g')
          sed -i'' "3s|.*| to = \"https://github.com/ojkelly/yarn.build/releases/download/$TAGNAME/plugin-build.js\"|" netlify.toml

      # Commit new version
     - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update release version to ${{ github.ref }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-release-version
          delete-branch: true
          title: 'release: Update release version to  ${{ github.ref }}'
          labels: |
            report
            automated pr
          assignees: ojkelly
          reviewers: ojkelly
          team-reviewers: |
            owners
            maintainers
          draft: false